apiVersion: v1
kind: Service
metadata:
  name: '{{ branch }}-error-backend'
  namespace: 'ingress-nginx'
spec:
  ports:
  - name: openresty
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: '{{ app }}-{{ branch }}-{{ build }}'
  sessionAffinity: None
  type: ClusterIP